Curriculum:
  StartEZ:
    file_name: "StartEZBatch.exe"
    mean_reward: 5.8
    episode_mean: 36
    cycles: 10
  StartSpawner:
    file_name: "StartSpawnerBatch.exe"
    mean_reward: 2.0
    episode_mean: 36
    cycles: 5
  Observe:
    file_name: "ObserveBatch.exe"
    mean_reward: -24.0
    episode_mean: 36
    cycles: 5
  StartCorridor:
    file_name: "StartCorridoioBatch.exe"
    mean_reward: 3.0
    episode_mean: 36
    cycles: 5
  Turn22Dynamic:
    file_name: "Turn22DynamicBatch.exe"
    mean_reward: 10.0
    episode_mean: 36
    cycles: 5
  Turn22Obstacles:
    file_name: "Turn22ObstaclesBatch.exe"
    mean_reward: 1.0
    episode_mean: 36
    cycles: 5



