Curriculum:
  StartEZ:
    file_name: "StartEZBatch.exe"
    mean_reward: 5.7
    episode_mean: 36
    cycles: 10
  #StartSpawner:
  #  file_name: "StartSpawnerBatch.exe"
  #  mean_reward: 3.0
  #  episode_mean: 36
  #  cycles: 5
  Observe:
    file_name: "ObserveBatch.exe"
    mean_reward: -24.0
    episode_mean: 36
    cycles: 5
  #StartCorridor:
  #  file_name: "StartCorridoioBatch.exe"
  #  mean_reward: 4.0
  #  episode_mean: 36
  #  cycles: 5
  Turn22Dynamic:
    file_name: "Turn22DynamicBatch.exe"
    mean_reward: 10.0
    episode_mean: 36
    cycles: 5
  Turn22Obstacles:
    file_name: "Turn22ObstaclesBatch.exe"
    mean_reward: 10.0
    episode_mean: 36
    cycles: 5
  Corridoio3vs3:
    file_name: "Corridoio3vs3Batch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 5
  NarrowDoor:
    file_name: "NarrowDoorBatch.exe"
    mean_reward: 5.0
    episode_mean: 36
    cycles: 5
  T-Junction:
    file_name: "T-JunctionBatch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 5
  Incrocio4:
    file_name: "Incrocio4Batch.exe"
    mean_reward: 5.0
    episode_mean: 36
    cycles: 5
  NarrowDoorDouble:
    file_name: "NarrowDoorDoubleBatch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 5



