Curriculum:
  StartEZ:
    file_name: "StartEZBatch.exe"
    mean_reward: 5.8
    episode_mean: 36
    cycles: 10
  Start:
    file_name: "StartBatch.exe"
    mean_reward: 3.0
    episode_mean: 36
    cycles: 5
  Observe:
    file_name: "ObserveBatch.exe"
    mean_reward: -24.0
    episode_mean: 36
    cycles: 5
  StartCorridor:
    file_name: "StartCorridorBatch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 15
  Turns:
    file_name: "TurnsBatch.exe"
    mean_reward: 10.0
    episode_mean: 36
    cycles: 10
  TurnObstacles:
    file_name: "TurnsObstaclesBatch.exe"
    mean_reward: 10.0
    episode_mean: 36
    cycles: 10
  NarrowDoor:
    file_name: "NarrowDoorBatch.exe"
    mean_reward: 5.0
    episode_mean: 36
    cycles: 15
  Corridor3vs3:
    file_name: "Corridor3vs3Batch.exe"
    mean_reward: 2.0 #4.0
    episode_mean: 36
    cycles: 15
  T-Junction:
    file_name: "T-JunctionBatch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 5
  Intersection4:
    file_name: "Intersection4Batch.exe"
    mean_reward: 2.5 #5.0
    episode_mean: 36
    cycles: 15
  NarrowDoorDouble:
    file_name: "NarrowDoorDoubleBatch.exe"
    mean_reward: 4.0
    episode_mean: 36
    cycles: 15
Test:
  Anchor:
    file_name: "AnchorBatch.exe"
    mean_reward: 0.0
    episode_mean: 36
    cycles: 5
  CurveC:
    file_name: "CurveCBatch.exe"
    mean_reward: 0.0
    episode_mean: 36
    cycles: 5
  Omega:
    file_name: "OmegaBatch.exe"
    mean_reward: 0.0
    episode_mean: 36
    cycles: 5
  DoubleChoice:
    file_name: "DoubleChoiceBatch.exe"
    mean_reward: 0.0
    episode_mean: 36
    cycles: 5


