Curriculum:
  StartEz:
    mean_reward: 5.7
    episode_mean: 108
    cycles: 7
  Start:
    mean_reward: 3.0
    episode_mean: 36
    cycles: 5
  CorridorObjectiveSmall:
    mean_reward: 3.0
    episode_mean: 100
    cycles: 12
  CorridorObjective:
    mean_reward: 3.0
    episode_mean: 100
    cycles: 12
  StartObjectiveRandom:
    mean_reward: 4.0
    episode_mean: 150
    cycles: 11
  StartObjectiveRandom2:
    mean_reward: 5.0
    episode_mean: 100
    cycles: 20
  CorridorObjtFacile:
    mean_reward: 4.5
    episode_mean: 150
    cycles: 17
  CorridorObjtMedio:
    mean_reward: 4.5
    episode_mean: 150
    cycles: 17
  CorridorObjtMedioTarget:
    mean_reward: 4.0
    episode_mean: 150
    cycles: 17
  CorridorObjt:
    mean_reward: 4.0
    episode_mean: 100
    cycles: 25
  CorridorObjtAngolo:
    mean_reward: 3.5
    episode_mean: 100
    cycles: 20
  Horseshoe:
    mean_reward: 3.5
    episode_mean: 100
    cycles: 20